version: "3.7"

services:
  redis:
    image: redis
    container_name: 'redis'
    restart: always
    command: redis-server
    ports:
      - '6379:6379'

  chat:
    build: ./chat
    container_name: 'chat'
    restart: always
    env_file:
      - chat/.env
    environment:
      REDIS_HOST: redis
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    ports:
      - '8000:8000'

  nginx:
    build: ./nginx
    container_name: 'nginx'
    restart: always
    depends_on:
      - chat
    ports:
      - "80:80"

