version: "3.7"


services:
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - '6379:6379'

  chat:
    build: ./chat
    container_name: 'chat'
    env_file:
      - chat/.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    ports:
      - '8000:8000'

  nginx:
    build: ./nginx
    container_name: 'nginx'
    restart: always
    ports:
      - "80:80"
    depends_on:
      - chat

