# Generated by Django 4.1.1 on 2023-01-04 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDialog',
            new_name='UserChat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_status_id',
            new_name='message_status',
        ),
        migrations.AlterModelTable(
            name='userchat',
            table='user_chats',
        ),
    ]
