# Generated by Django 4.1.1 on 2023-01-22 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_messages', '0002_rename_userdialog_userchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat_messages.userchat'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together={('user1', 'user2')},
        ),
    ]
